### ISSUE TITLE
Optimise the number and distribution of energy bins 

### ISSUE THREAD

**Issue by orelgueta** [cta-observatory/iact_event_types#14]
We can probably improve performance if we optimise the number and distribution of energy bins. Worth a try at least.

**Comment by TarekHC** [comment]
Yes, and this is somehow related to #11. It might very well be that the performance is heavily influenced by the training statistics of each bin (and not only the different "physics" associated to the different energy bins).

**Comment by JBernete** [comment]
I'm testing this in the branch test_energy_binning. It looks like we can safely reduce the number of energy bins in the training, but I'm still not sure if we can reduce it to just one. The branch is still a little buggy, so I'll make the PR after holidays.

**Comment by orelgueta** [comment]
OK, no problem!

**Comment by JBernete** [comment]
I tested with 1, 3, 5, 10 and 20 (current) equally filled energy bins with the test_energy_binning branch, which is now ready for the PR.
I think the confusion matrix is the best way to compare between these, because even if the binning in the training is different, we can test the with the same binning (the one we use later to compute sensitivity).
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/865183fa-6f39-467e-8fb6-baf6f8422a0d)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/faae8952-8f56-403c-baa4-19896590ad53)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/56f6b0b4-5617-4c12-a721-bd8066655f92)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/9b08e50a-d222-4dcc-8b6f-6dd2dfdea104)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/a12a6d0e-60db-4e36-aa09-31ddd93345a0)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/cd072bca-6816-4b1f-9495-e9e563dc0605)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/681ebe51-c484-4f83-b6e7-32869c6ffb76)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/f6916013-6455-4d28-9c88-8c69bf6182bf)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/d1e7a634-c42c-4909-b8b6-c2083c6ccc6c)
![image](https://github.com/cta-observatory/iact_event_types/assets/73588186/ba0a6c0c-ff30-421c-bd80-076c3f8ab712)

I know they are too many plots and is difficult to see because they are all really similar. My conclusion is that the binning is not affecting too much, but I can see that the best performance is achieved when the number of bins is reduced (3 or 5), but not 1. So I would stop using 20 bins by default and probably reduce it to 3. What do you think?

**Comment by orelgueta** [comment]
I focused on the case of 3 event types for the following (because I hope it is the case that will actually be used).

It seems to me that the difference is only seen at the highest energy bins, above 50 TeV. For all the bins below I think the difference is small enough to be considered within statistical fluctuations. For those very-high-energy bins, we do benefit from the increase in energy bins in the training. This is expected considering the steep energy distribution. The NN will naturally focus on the more abundant low-energy examples it sees.
The difference is not large though and probably not worth the increase in complication. One could also argue that above 50 TeV the differences we see are inconsequential considering the amount of events we have at those energies and their inherent good quality to begin with. 

So, to make a long story short, I think it won't make a difference if we reduce the number of energy bins. The best compromise between performance and simplicity is if we use 10 bins, but going down to three wouldn't be too bad either. If you think using three bins is simpler/easier than 10, let's use that. Otherwise, perhaps using 10 bins is best.

**Comment by JBernete** [comment]
Yes, you're right, the highest energy bins work better with 10 bins, so let's use that.

**Comment by orelgueta** [comment]
OK!
